pmstore/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pmstore.Data;
using pmstore.Data.Service;
using pmstore.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace pmstore.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly IAlbumsService _service;

        public AlbumsController(IAlbumsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allAlbums = await _service.GetAllAsync(n => n.Streaming);
            return View(allAlbums);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allAlbums = await _service.GetAllAsync(n => n.Streaming);

            if (!string.IsNullOrEmpty(searchString))
            {

                var filteredResultNew = allAlbums.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }
            return View(allAlbums);
        }

        // Albums/Detail/1
        public async Task<IActionResult> Detail(int id)
        {
            var albumDetail = await _service.GetAlbumByIdAsync(id);
            return View(albumDetail);
        }

        // Albums/Create
        public async Task<IActionResult> Create()
        {
            var albumDropdownsData = await _service.GetNewAlbumDropdownsValues();

            ViewBag.Streamings = new SelectList(albumDropdownsData.Streamings, "Id", "Name");
            ViewBag.Producers = new SelectList(albumDropdownsData.Producers, "Id", "FullName");
            ViewBag.Artists = new SelectList(albumDropdownsData.Artists, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewAlbumVM album)
        {
            if (!ModelState.IsValid)
            {
                var albumDropdownsData = await _service.GetNewAlbumDropdownsValues();

                ViewBag.Streamings = new SelectList(albumDropdownsData.Streamings, "Id", "Name");
                ViewBag.Producers = new SelectList(albumDropdownsData.Producers, "Id", "FullName");
                ViewBag.Artists = new SelectList(albumDropdownsData.Artists, "Id", "FullName");

                return View(album);
            }

            await _service.AddNewAlbumAsync(album);
            return RedirectToAction(nameof(Index));
        }

        // Albums/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var albumDetail = await _service.GetAlbumByIdAsync(id);
            if (albumDetail == null) return View("Not Found");

            var response = new NewAlbumVM()
            {
                Id = albumDetail.Id,
                Name = albumDetail.Name,
                Description = albumDetail.Description,
                Price = albumDetail.Price,
                ReleaseDate = albumDetail.ReleaseDate,
                ImageURL = albumDetail.ImageURL,
                Genre = albumDetail.Genre,
                StreamingId = albumDetail.StreamingId,
                ProducerId = albumDetail.ProducerId,
                ArtistIds = albumDetail.Artists_Albums.Select(n => n.ArtistId).ToList(),
            };

            var albumDropdownsData = await _service.GetNewAlbumDropdownsValues();
            ViewBag.Streamings = new SelectList(albumDropdownsData.Streamings, "Id", "Name");
            ViewBag.Producers = new SelectList(albumDropdownsData.Producers, "Id", "FullName");
            ViewBag.Artists = new SelectList(albumDropdownsData.Artists, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewAlbumVM album)
        {
            if (id != album.Id) return View("Not Found");

            if (!ModelState.IsValid)
            {
                var albumDropdownsData = await _service.GetNewAlbumDropdownsValues();

                ViewBag.Streamings = new SelectList(albumDropdownsData.Streamings, "Id", "Name");
                ViewBag.Producers = new SelectList(albumDropdownsData.Producers, "Id", "FullName");
                ViewBag.Artists = new SelectList(albumDropdownsData.Artists, "Id", "FullName");

                return View(album);
            }

            await _service.UpdateAlbumAsync(album);
            return RedirectToAction(nameof(Index));
        }


    }
}

pmstore/Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;
using pmstore.Data;
using pmstore.Data.Service;
using pmstore.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace pmstore.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly IArtistsService _service;

        public ArtistsController(IArtistsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(); 
            return View(data);
        }

        // Artists/Create
        public IActionResult Create()
        { 
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePctureURL, Bio")] Artist artist)
        {
            if (ModelState.IsValid)
            { 
                return View(artist);
            }
            await _service.AddAsync(artist);
            return RedirectToAction(nameof(Index));
        }

        //  Artists/Detail/1
        public async Task<IActionResult> Detail(int id)
        {
            var artistDetails = await _service.GetByIdAsync(id);

            if (artistDetails == null) return View("Not Found");
            return View(artistDetails); 
        }

        // Artists/Update
        public async Task<IActionResult> Edit(int id)
        {
            var artistDetails = await _service.GetByIdAsync(id);
            if (artistDetails == null) return View("Not Found");
            return View(artistDetails);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, ProfilePctureURL, Bio")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                return View(artist);
            }
            await _service.updateAsync(id, artist);
            return RedirectToAction(nameof(Index));
        }

        //Get: Artists/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var artistDetail = await _service.GetByIdAsync(id);
            if (artistDetail == null) return View("Not Found");
            return View(artistDetail);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artistDetail = await _service.GetByIdAsync(id);
            if (artistDetail == null) return View("Not Found");

            await _service.deleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

pmstore/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using pmstore.Data;
using pmstore.Data.Service;
using pmstore.Models;
using System.Linq;
using System.Threading.Tasks;

namespace pmstore.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;

        public ProducersController(IProducersService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }
        
        // producers/detail/1
        public async Task<IActionResult> Detail(int id)
        {
            var producerDetail = await _service.GetByIdAsync(id);
            if (producerDetail == null) return View("Not Found");
            return View(producerDetail);
        }

        // producer/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);

            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        // producers/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("Not Found");
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);

            if (id == producer.Id)
            {
                await _service.updateAsync(id, producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        // producers/delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var producerDetail = await _service.GetByIdAsync(id);
            if (producerDetail == null) return View("Not Found");
            return View(producerDetail);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetail = await _service.GetByIdAsync(id);
            if (producerDetail == null) return View("Not Found");

            await _service.deleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

pmstore/Controllers/StreamingsController.cs
using Microsoft.AspNetCore.Mvc;
using pmstore.Data;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using pmstore.Data.Service;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using pmstore.Models;

namespace pmstore.Controllers
{
    public class StreamingsController : Controller
    {
        private readonly IStreamingsService _service;

        public StreamingsController(IStreamingsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allStreamings = await _service.GetAllAsync();
            return View(allStreamings);
        }

        // Streaming/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Streaming streaming)
        {
            if (!ModelState.IsValid) return View(streaming);
            await _service.AddAsync(streaming);
            return RedirectToAction(nameof(Index));
        }

        // Streaming/Detail/1
        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            var streamDetails = await _service.GetByIdAsync(id);
            if (streamDetails == null) return View("Not Found");
            return View(streamDetails);
        }

        // Streaming/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var streamDetails = await _service.GetByIdAsync(id);
            if (streamDetails == null) return View("Not Found");
            return View(streamDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Streaming streaming)
        {
            if (!ModelState.IsValid) return View(streaming);
            await _service.updateAsync(id, streaming);
            return RedirectToAction(nameof(Index));
        }

        // Streaming/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var streamDetails = await _service.GetByIdAsync(id);
            if (streamDetails == null) return View("Not Found");
            return View(streamDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var streamDetails = await _service.GetByIdAsync(id);
            if (streamDetails == null) return View("Not Found");

            await _service.deleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

pmstore/Views/Shared/Not Found.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Albums" asp-action="Index">Home Page</a>
    </div>
</div>

pmstore/Views/Shared/_CreateItem.cshtml
@model string;

<div style="position:fixed; right: 60px; bottom: 60px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success"> <i class="bi bi-plus-circle"></i> ADD</a>
</div>

pmstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Personal Music Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Albums" asp-action="Index">Personal Music Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Albums" asp-action="Index"><i class="bi bi-disc"></i> Albums</a>
                        </li>
                        
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Manage
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-collection-play"></i> Producer</a>
                                <a class="dropdown-item" asp-controller="Streamings" asp-action="Index"><i class="bi bi-music-note-beamed"></i> Streaming</a>
                                <a class="dropdown-item" asp-controller="Artists" asp-action="Index"><i class="bi bi-person-check"></i>Artist</a>
                                </div>
                            </li>
                        

                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Albums" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for An Album..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-warning my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>

    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Personal Music Store
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>